targets:
  $default:
    builders:
      json_serializable:json_serializable:
        enabled: true
        generate_for:
          include:
            - lib/features/**/domain/**.dart
      freezed:freezed:
        enabled: true
        generate_for:
          include:
            - lib/features/**/domain/**.dart