name: signsyncai
description: "SignSyncAI enhances communication for students especially with those hearing and speech disabilities. Effortlessly scan AR barcodes, convert speech to text, and get instant AI-powered conversation summaries."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  easy_localization: ^3.0.7
  intl: ^0.19.0

  connectivity_plus: ^6.0.3
  flutter_rearch: ^1.6.7
  rearch: ^1.10.1

  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  cloud_firestore: ^5.0.0
  google_sign_in: ^6.2.1
  firebase_app_check: ^0.3.0
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  firebase_vertexai: ^0.2.1

  faker_dart: ^0.2.2
  flutter_secure_storage: ^9.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  auto_size_text: ^3.0.0
  flutter_native_splash: ^2.4.0
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  native_toast: ^0.0.2
  phosphor_flutter: ^2.1.0
  skeletonizer: ^1.3.0
  toastification: ^2.0.0
  websafe_svg: ^3.0.1+1
  wolt_modal_sheet: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  build_runner: ^2.4.11

  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - google_fonts/
    - i18n/
    - assets/images/
    - assets/lottie/
