name: signsyncai
description: "SignSyncAI enhances communication for students especially with those hearing and speech disabilities. Effortlessly scan AR barcodes, convert speech to text, and get instant AI-powered conversation summaries."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.0
  connectivity_plus: ^6.0.3
  easy_localization: ^3.0.7
  firebase_app_check: ^0.3.0
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  firebase_vertexai: ^0.2.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_secure_storage: ^9.2.2
  freezed_annotation: ^2.4.1
  go_router: ^14.1.4
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.5.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  lottie: ^3.1.2
  native_toast: ^0.0.2
  phosphor_flutter: ^2.1.0
  riverpod_annotation: ^2.3.5
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  riverpod_lint: ^2.3.10
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4

flutter:
  uses-material-design: true

  assets:
    - google_fonts/
    - assets/translations/
    - assets/images/
    - assets/lottie/
