// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbE4mjpjjb9DIpjkzAiL8K9bZ7MVBF7y4',
    appId: '1:1063343818537:android:c22b30a41df92eaf44d938',
    messagingSenderId: '1063343818537',
    projectId: 'sign-sync-ai',
    storageBucket: 'sign-sync-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSoZFRXyxqpZIx4T33vinYZ9vjV-af9FU',
    appId: '1:1063343818537:ios:9dd6c6fc57c4d70e44d938',
    messagingSenderId: '1063343818537',
    projectId: 'sign-sync-ai',
    storageBucket: 'sign-sync-ai.appspot.com',
    androidClientId: '1063343818537-8bmf0jnog9cqpm4dan0i620i6a27hag0.apps.googleusercontent.com',
    iosClientId: '1063343818537-sbtqva1aufbk66o077o5lv76qci63npq.apps.googleusercontent.com',
    iosBundleId: 'id.ac.ftiunmer.signsyncai',
  );

}